//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: observable (OnPropertyChanged) enabled
    
// Generated from: protos/MsgFPS.proto
namespace Msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NcHandShake")]
  public partial class NcHandShake : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public NcHandShake() {}
    
    private string _Token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Token
    {
      get { return _Token; }
      set { _Token = value; OnPropertyChanged(@"Token"); }
    }
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NsHandShake")]
  public partial class NsHandShake : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public NsHandShake() {}
    
    private long _PlayerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long PlayerId
    {
      get { return _PlayerId; }
      set { _PlayerId = value; OnPropertyChanged(@"PlayerId"); }
    }
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NsRoomUpdate")]
  public partial class NsRoomUpdate : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public NsRoomUpdate() {}
    
    private readonly global::System.Collections.Generic.List<long> _ExistPlayers = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ExistPlayers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> ExistPlayers
    {
      get { return _ExistPlayers; }
    }
  
    private long _AddedPlayer = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"AddedPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long AddedPlayer
    {
      get { return _AddedPlayer; }
      set { _AddedPlayer = value; OnPropertyChanged(@"AddedPlayer"); }
    }
    private long _RemovedPlayer = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"RemovedPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long RemovedPlayer
    {
      get { return _RemovedPlayer; }
      set { _RemovedPlayer = value; OnPropertyChanged(@"RemovedPlayer"); }
    }
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NcRoomCmd")]
  public partial class NcRoomCmd : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public NcRoomCmd() {}
    
    private string _Cmd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Cmd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Cmd
    {
      get { return _Cmd; }
      set { _Cmd = value; OnPropertyChanged(@"Cmd"); }
    }
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NsRoomNotify")]
  public partial class NsRoomNotify : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public NsRoomNotify() {}
    
    private string _Cmd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Cmd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Cmd
    {
      get { return _Cmd; }
      set { _Cmd = value; OnPropertyChanged(@"Cmd"); }
    }
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PbSyncObjAtt")]
  public partial class PbSyncObjAtt : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public PbSyncObjAtt() {}
    
    private int _Index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Index
    {
      get { return _Index; }
      set { _Index = value; OnPropertyChanged(@"Index"); }
    }
    private int _PbSyncObjAttType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PbSyncObjAttType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PbSyncObjAttType
    {
      get { return _PbSyncObjAttType; }
      set { _PbSyncObjAttType = value; OnPropertyChanged(@"PbSyncObjAttType"); }
    }
    private int _N32Val = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"N32Val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int N32Val
    {
      get { return _N32Val; }
      set { _N32Val = value; OnPropertyChanged(@"N32Val"); }
    }
    private long _N64Val = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"N64Val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long N64Val
    {
      get { return _N64Val; }
      set { _N64Val = value; OnPropertyChanged(@"N64Val"); }
    }
    private string _StrVal = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"StrVal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string StrVal
    {
      get { return _StrVal; }
      set { _StrVal = value; OnPropertyChanged(@"StrVal"); }
    }
    private float _FloatVal = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"FloatVal", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float FloatVal
    {
      get { return _FloatVal; }
      set { _FloatVal = value; OnPropertyChanged(@"FloatVal"); }
    }
    private bool _BoolVal = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"BoolVal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool BoolVal
    {
      get { return _BoolVal; }
      set { _BoolVal = value; OnPropertyChanged(@"BoolVal"); }
    }
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PbSyncObj")]
  public partial class PbSyncObj : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public PbSyncObj() {}
    
    private long _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Id
    {
      get { return _Id; }
      set { _Id = value; OnPropertyChanged(@"Id"); }
    }
    private string _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Type
    {
      get { return _Type; }
      set { _Type = value; OnPropertyChanged(@"Type"); }
    }
    private readonly global::System.Collections.Generic.List<Msg.PbSyncObjAtt> _Atts = new global::System.Collections.Generic.List<Msg.PbSyncObjAtt>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Atts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Msg.PbSyncObjAtt> Atts
    {
      get { return _Atts; }
    }
  
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NsSyncObjAdded")]
  public partial class NsSyncObjAdded : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public NsSyncObjAdded() {}
    
    private readonly global::System.Collections.Generic.List<Msg.PbSyncObj> _Added = new global::System.Collections.Generic.List<Msg.PbSyncObj>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Added", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Msg.PbSyncObj> Added
    {
      get { return _Added; }
    }
  
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NsSyncObjRemoved")]
  public partial class NsSyncObjRemoved : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public NsSyncObjRemoved() {}
    
    private readonly global::System.Collections.Generic.List<long> _Removed = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Removed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> Removed
    {
      get { return _Removed; }
    }
  
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NsSyncObjRefreshed")]
  public partial class NsSyncObjRefreshed : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public NsSyncObjRefreshed() {}
    
    private readonly global::System.Collections.Generic.List<Msg.PbSyncObj> _Refreshed = new global::System.Collections.Generic.List<Msg.PbSyncObj>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Refreshed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Msg.PbSyncObj> Refreshed
    {
      get { return _Refreshed; }
    }
  
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NsSyncSceneEnter")]
  public partial class NsSyncSceneEnter : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public NsSyncSceneEnter() {}
    
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NsSyncSceneExit")]
  public partial class NsSyncSceneExit : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public NsSyncSceneExit() {}
    
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NcRPC")]
  public partial class NcRPC : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public NcRPC() {}
    
    private long _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Id
    {
      get { return _Id; }
      set { _Id = value; OnPropertyChanged(@"Id"); }
    }
    private string _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Type
    {
      get { return _Type; }
      set { _Type = value; OnPropertyChanged(@"Type"); }
    }
    private byte[] _Bytes;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Bytes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Bytes
    {
      get { return _Bytes; }
      set { _Bytes = value; OnPropertyChanged(@"Bytes"); }
    }
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NsRPC")]
  public partial class NsRPC : global::ProtoBuf.IExtensible, global::System.ComponentModel.INotifyPropertyChanged
  {
    public NsRPC() {}
    
    private long _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Id
    {
      get { return _Id; }
      set { _Id = value; OnPropertyChanged(@"Id"); }
    }
    private string _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Type
    {
      get { return _Type; }
      set { _Type = value; OnPropertyChanged(@"Type"); }
    }
    private byte[] _Bytes;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Bytes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Bytes
    {
      get { return _Bytes; }
      set { _Bytes = value; OnPropertyChanged(@"Bytes"); }
    }
    public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    protected virtual void OnPropertyChanged(string propertyName)
      { if(PropertyChanged != null) PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName)); }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PbSyncObjAttType")]
    public enum PbSyncObjAttType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Int32", Value=0)]
      Int32 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Int64", Value=1)]
      Int64 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"String", Value=2)]
      String = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Float", Value=3)]
      Float = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Double", Value=4)]
      Double = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Bool", Value=5)]
      Bool = 5
    }
  
}